# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1skaSV106lxshgZjE5kleKpNZkVJz4x8N
"""

# Перевірка потрібних бібліотек та версій
import sys
import subprocess

def install(package):
    subprocess.check_call([sys.executable, "-m", "pip", "install", package])

# Перевіряємо NumPy
import numpy as np
np_version = np.__version__

print(f"NumPy version: {np_version}")

# Якщо NumPy > 2.0, то ставимо потрібну
if int(np_version.split('.')[0]) >= 2:
    print("⚙️ Downgrading NumPy to 1.26.4 for neurolab compatibility...")
    install('numpy==1.26.4')
    print("✅ NumPy downgraded. Please restart runtime manually: Runtime → Restart Runtime")
    raise SystemExit("⏹️ STOP. Restart runtime and run this cell again!")

# Встановлюємо neurolab, якщо ще не встановлено
try:
    import neurolab as nl
except ImportError:
    print("⚙️ Installing neurolab...")
    install('git+https://github.com/zueve/neurolab.git')
    import neurolab as nl
    print("✅ neurolab installed!")

# --- Власне код завдання ---

# Вхідні дані
target = [[-1, 1, -1, -1, 1, -1, -1, 1, -1],
          [1, 1, 1, 1, -1, 1, 1, -1, 1],
          [1, -1, 1, 1, 1, 1, 1, -1, 1],
          [1, 1, 1, 1, -1, -1, 1, -1, -1],
          [-1, -1, -1, -1, 1, -1, -1, -1, -1]]

input = [[-1, -1, 1, 1, 1, 1, 1, -1, 1],
         [-1, -1, 1, -1, 1, -1, -1, -1, -1],
         [-1, -1, -1, -1, 1, -1, -1, 1, -1]]

# Створення та тренування нейронної мережі Хемінга
net = nl.net.newhem(target)

# Тест на тренувальних даних
output = net.sim(target)
print("\nTest on train samples (must be [0, 1, 2, 3, 4]):")
print(np.argmax(output, axis=0))

# Тест на одному зразку
output = net.sim([input[0]])
print("\nOutputs on recurrent cycle:")
print(np.array(net.layers[1].outs))

# Тест на всіх тестових зразках
output = net.sim(input)
print("\nOutputs on test sample:")
print(output)